name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and run command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EDUCATION_LA_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_EDUCATION_LABS_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Conexión SSH exitosa"
            if cd /home/${{ secrets.SSH_USER }}/${{ github.event.repository.name }}; then
              echo "reconstruyendo imagen..."
            else
              echo "Clonando imagen..."
              cd /home/${{ secrets.SSH_USER }}
              sudo git clone ${{ github.event.repository.ssh_url }}
              cd /home/${{ secrets.SSH_USER }}/${{ github.event.repository.name }}
            fi
            sudo git checkout ${{ github.ref_name }}
            sudo git pull
            sudo cp .deployment/.env-main .env
            sudo docker compose -f docker-compose.yml --env-file .env up -d --build
            sudo sh create-tag.sh
